name: sofomo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^10.1.2
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^7.0.8
  talker_dio_logger: ^2.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
